#%RAML 1.0 NamedExample

value:
    firstName: Max
    lastName: Doe
    address: holly st.
    postal: Auckland
    country: UK
    miles: 100
    creationDate: 2016-02-28T16:41:41.090Z
    type: personal