#%RAML 1.0 NamedExample

value:
  -
    firstName: Max
    lastName: Doe
    address: holly st.
    postal: Auckland
    country: UK
    miles: 10
    type: personal
  -
    firstName: Marc
    lastName: Doe
    address: hoy st.
    postal: Bath
    country: IT
    miles: 50
    type: personal